### ISSUE TITLE
Seemingly excessive permissions

### ISSUE THREAD

**Issue by ynoauun** [writeas/paste-chrome#4]
Why does it need to communicate with any local network or internet machine in the chromeos app?

**Comment by thebaer** [comment]
This project is actually for the Chrome **extension**, not the Chrome OS app.

But the Chrome OS app needs those permissions to publish a post (and interact with published posts) on https://write.as. Otherwise everything happens locally -- there's no communication with the internet. Feel free to email me at hello@write.as if you have more questions.
